---
- hosts: 127.0.0.1
  vars:
     helm_chart_url: "https://oteemo.github.io/charts"
  become: false
  tasks:
  - name: Create Nexus persistence Volume
    become: false
    command: kubectl apply -f ./nexus-pv.yaml

  - name: Create Nexus Service Account
    become: false
    command: kubectl apply -f ./nexus-sa.yaml
 
  - name: Add helm repo
    kubernetes.core.helm_repository:
        name: nexus
        repo_url: "{{ helm_chart_url }}"

  - name: Install Jenkins Chart
    kubernetes.core.helm:
        name: nexus
        namespace: build
        create_namespace: true
        chart_ref: nexus/sonatype-nexus
        values_files:
           - ./nexus-values.yaml
