---
- hosts: 127.0.0.1
  become: false
  tasks:
  - name: Uninstall Nexus Chart
    kubernetes.core.helm:
        name: nexus
        namespace: build
        state: absent
        wait: true

  - name: Delete Nexus persistence Volume
    become: false
    command: kubectl delete -f ./nexus-pv.yaml

  - name: Delete Nexus Service Account
    become: false
    command: kubectl delete -f ./nexus-sa.yaml
