apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-test-pv
  namespace: test
spec:
  storageClassName: mysql-test-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: test
spec:
  storageClassName: mysql-test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
